title: Domum Core
description: Home automation // observability portal
theme: dark
color: violet
target: _self
hideVersion: true
disableUpdateCheck: true
statusStyle: dot
headerStyle: clean
iconStyle: theme
fullWidth: true
useEqualHeights: true
quicklaunch:
  searchDescriptions: true
  provider: duckduckgo
  target: _blank
  mobileButtonPosition: bottom-right
layout:
  Overview:
    tab: Overview
    style: row
    columns: 1
  Home Automation:
    tab: Services
    style: row
    columns: 3
  Infrastructure:
    tab: Operations
    style: row
    columns: 4
  Applications:
    tab: Services
    style: row
    columns: 3
  External Systems:
    tab: Operations
    style: row
    columns: 3
  Automation Docs:
    tab: Reference
    style: row
    columns: 4
  Operations Docs:
    tab: Reference
    style: row
    columns: 4
