title: domum-core
description: Home automation // observability portal
theme: dark
color: slate
target: _self
hideVersion: true
disableUpdateCheck: true
statusStyle: dot
headerStyle: boxedWidgets
iconStyle: theme
fullWidth: true
useEqualHeights: true
cardBlur: md
background:
  image: /images/domum-background.svg
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 30
quicklaunch:
  searchDescriptions: true
  provider: google
  target: _blank
  mobileButtonPosition: bottom-right
layout:
  Core Status:
    tab: System
    style: row
    columns: 3
  Calendar:
    tab: System
    style: row
    columns: 1
  Network Operations:
    tab: System
    style: row
    columns: 4
  Host Fleet:
    tab: System
    style: row
    columns: 3
  Home Automation:
    tab: System
    style: row
    columns: 3
  Infrastructure:
    tab: Apps
    style: row
    columns: 4
  Applications:
    tab: Apps
    style: row
    columns: 3
  Security:
    tab: Apps
    style: row
    columns: 3
  Media Services:
    tab: Media
    style: row
    columns: 3
  Media Infrastructure:
    tab: Media
    style: row
    columns: 3
  Feed Bookmarks:
    tab: Feeds
    style: row
    columns: 4
  Glance:
    tab: Feeds
    style: row
    columns: 1
