name: domum

networks:
  domum-proxy:
    name: domum-proxy
    driver: bridge
  domum-internal:
    name: domum-internal
    driver: bridge
  domum-data:
    name: domum-data
    driver: bridge

volumes:
  traefik-letsencrypt:
  uptime-kuma-data:
  portainer-data:
  jellyfin-config:
  jellyfin-cache:
