services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    command:
      - serve
    networks:
      - domum-proxy
    environment:
      - TZ=America/New_York
      - NTFY_BASE_URL=https://ntfy.${DOMUM_DOMAIN}
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=deny-all
      - NTFY_BEHIND_PROXY=true
      - NTFY_ATTACHMENT_CACHE_DIR=/var/lib/ntfy/attachments
      - NTFY_ATTACHMENT_TOTAL_SIZE_LIMIT=250M
      - NTFY_ATTACHMENT_FILE_SIZE_LIMIT=15M
      - NTFY_ENABLE_LOGIN=true
      - NTFY_ENABLE_SIGNUP=false
      - NTFY_UPSTREAM_BASE_URL=https://ntfy.sh
    volumes:
      - /opt/domum-core/compose/monitoring/ntfy/data:/var/lib/ntfy
    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.ntfy.rule=Host(`ntfy.${DOMUM_DOMAIN}`)
      - traefik.http.routers.ntfy.entrypoints=websecure
      - traefik.http.routers.ntfy.tls=true
      - traefik.http.routers.ntfy.tls.certresolver=cf
      - traefik.http.routers.ntfy.middlewares=securityHeaders@file
      - traefik.http.services.ntfy.loadbalancer.server.port=80
    profiles:
      - core

networks:
  domum-proxy:
    external: true
