services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    networks:
      - domum-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.excalidraw.rule=Host(`draw.${DOMUM_DOMAIN}`)
      - traefik.http.routers.excalidraw.entrypoints=websecure
      - traefik.http.routers.excalidraw.tls=true
      - traefik.http.routers.excalidraw.tls.certresolver=cf
      - traefik.http.routers.excalidraw.middlewares=securityHeaders@file,forwardedHeaders@file
      - traefik.http.services.excalidraw.loadbalancer.server.port=80
    profiles:
      - core

networks:
  domum-proxy:
    external: true
