services:
  adguard-home:
    image: adguard/adguardhome:latest
    container_name: adguard-home
    restart: unless-stopped
    networks:
      - domum-proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /opt/domum-core/compose/networking/adguard/work:/opt/adguardhome/work
      - /opt/domum-core/compose/networking/adguard/conf:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.docker.network=domum-proxy
      - traefik.http.routers.dns.rule=Host(`dns.${DOMUM_DOMAIN}`)
      - traefik.http.routers.dns.entrypoints=websecure
      - traefik.http.routers.dns.tls=true
      - traefik.http.routers.dns.tls.certresolver=cf
      - traefik.http.routers.dns.middlewares=forwardedHeaders@file
      - traefik.http.services.dns.loadbalancer.server.port=80
    profiles:
      - core

networks:
  domum-proxy:
    external: true
